# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    security.access.role_voter:
        class: AppBundle\Security\AuthorizationVoter
        arguments: ["@service_container"]
        public: false
        tags:
            - { name: security.voter }
            
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - {name: form.type, alias: app_user_registration }
            
    app.files_type_extensions:
        class: AppBundle\Form\Extension\FichierTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }